### ISSUE TITLE
two general suggestions

### ISSUE THREAD

**Issue by practik** [soufianesakhi/youtube-playlist-helper#1]
Hi Soufiane, thank you for the extension! I haven't used it much yet but so far it works great.

I have two general suggestions; I hope you don't mind if I combine them both in one issue:

1. Could you add a privacy policy to the extension's page on AMO? It can be very short – see for example https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/privacy/ :-)

2. In the list of bookmarks folders, it seems a little strange that parent folders appear below their children:
![Bookmarks](https://user-images.githubusercontent.com/12074235/80051552-a33ff680-84d5-11ea-8726-844c0ef4826f.png)
Shouldn't the parents be listed first?

**Comment by soufianesakhi** [comment]
Thanks for the suggestions. They are now effective as of v1.0.2.
