### ISSUE TITLE
(Idea) Remember items added to the list

### ISSUE THREAD

**Issue by Vingolf** [soufianesakhi/youtube-playlist-helper#10]
First of all, thank you for this addon. 
It provides useful features for creating youtube playlists. 🙂 

Overall, creating a playlist from a list of links is working fine.√ 

I propose a minor feature for your addon: 

**Describe the new feature** 
I want to compile a list **within** the window of YouTube Playlist Helper 

**To Reproduce**
1. Paste a link into the window of YouTube Playlist Helper. 
2. Go to youtube and copy a second link. 
3. Reopen the window for lists within YouTube Playlist Helper. 
4. The first item has gone.  
5. You cannot create a list, but paste merely one item in this window. 

**Desired behaviour** 

1. Remember the previously added links. 
2. This will allow to add links to the list in YouTube Playlist Helper. 
3. When you click the button Create Playlist, the youtube playlist will be created and the items in this list become deleted.

**Comment by soufianesakhi** [comment]
This will be implemented once the playlist editor feature I'm currently working on is complete.

**Comment by soufianesakhi** [comment]
You can now create new playlists more intuitively using the 2.0.0 version that includes a playlist editor.
