### ISSUE TITLE
(Idea) Add an export function to support reordering playlists

### ISSUE THREAD

**Issue by Vingolf** [soufianesakhi/youtube-playlist-helper#11]
Exported links can be reordered with an external program and then be used to create a new playlist in changed order.

I want to open this features to discussion, since reordering a playlist is currently a bit cumbersome.

If YouTube Playlist Helper allows to export a playlist, this may simplifiy reordering the list with an external editor.

Useful ways to use the links could be if they were copied to clipboard, exported as a text file (playlist.txt) or shown in a popup window.

**Comment by soufianesakhi** [comment]
Currently there is nothing stored by the extension. So nothing to export.
Do you want instead to export open playlists ? I can for example open a popup window containing the playlist's videos as links.

**Comment by soufianesakhi** [comment]
This can be part of the future playlist editor, there will be an export button to export playlists.

**Comment by soufianesakhi** [comment]
For your information, you can now reorder playlist videos using the new playlist editor starting from v2.0.0.
The export button will follow soon.

**Comment by soufianesakhi** [comment]
Available in v2.1.0
