### ISSUE TITLE
Weird UI bug?

### ISSUE THREAD

**Issue by yuse4** [soufianesakhi/youtube-playlist-helper#14]

**Comment by soufianesakhi** [comment]
Hello, are you sure you are using this extension? 
- For Google Chrome: https://chrome.google.com/webstore/detail/youtube-playlist-helper/ibdakohjhchaagmccfedeejmeillongg
- For Firefox: https://addons.mozilla.org/en-US/firefox/addon/youtube-playlist-helper/

**Comment by yuse4** [comment]
Sorry about that,, wrote to wrong person.
