### ISSUE TITLE
Chrome Version 91.0.4472.114 (Official Build) (64-bit) manifest not found

### ISSUE THREAD

**Issue by tsalmela** [soufianesakhi/youtube-playlist-helper#16]
Hello,

After unzipping the extension and trying to install it to chrome in Windows you get error:
`Manifest file is missing or unreadable`
Fixed by moving manifest to root and adding src/'s to paths in the manifest.

**Comment by soufianesakhi** [comment]
Hello, thanks for opening the issue, but this is neither a feature nor a bug fix.
If you need to debug locally the extension, download the repository using the available links on GitHub and import the src folder directly to Google Chrome (Load unpacked) or Firefox (in about:debug).

**Comment by tsalmela** [comment]
To this day I thought the normal way of installing Chrome extensions was through drag&drop. My bad for opening this issue. Sorry for the trouble. :)
