### ISSUE TITLE
[Feature Request] Automatically Save the Queue list that has been created manually

### ISSUE THREAD

**Issue by Droyk** [soufianesakhi/youtube-playlist-helper#18]
So I recently started using the playlist editor 6 days ago as I didn't have the time before to check it out. 
so after using it seems like it's really hard for me to save the queue list. in the period of 6 days, I made some queue lists, forget to save them, and came back later to find out the browser got crashed and all of the queue lists that I made in the period of 6 days are gone. 
so it would be really convenient if you can add an option in the setting page to save the queue list automatically.

**Comment by soufianesakhi** [comment]
Did you create the lists with the extension? If so they are automatically saved in the "Recently created playlists" page of the playlist editor.

**Comment by Droyk** [comment]
> Did you create the lists with the extension? If so they are automatically saved in the "Recently created playlists" page of the playlist editor.

Forgot to mention it before, No! So it would be really convenient to provide an option to automatically save the queue list that has been created manually coz many times I'll be using the extension to create the queue lists & many times I'll be making them manually.

**Comment by soufianesakhi** [comment]
Hello, this is not applicable because often the user builds the queue gradually, saving the queue each time the user adds a video doesn't make sense. The user needs to manually save the playlist after starting playing the queue using the menu.

**Comment by Droyk** [comment]
>saving the queue each time the user adds a video doesn't make sense.

I disagree. you see I want to gather as much information as I can, so what used to happens is I used to right-click and open in a background tab now after opening some 20-30 videos. I tend to relax because the first task of curating them is over so I'll go do some other work and then get back to watch them now after watching some 2 - 3 videos. I then again open 2 to 3 related videos & now in just matter of minutes I would have 50 - 60 video tabs open & my browser used to be ready to crash and then I found this extension & then I got to know how time-saving, resource-saving and convenient queue list feature really is & now my habit of right-clicking open in the background is changing to just make a queue list. so now I don't have any video tabs instead what I have is queue lists tabs the problem is I still forget to save them I have this mental illness which makes me forget things really easily and make me procrastinate. & also as you said
>often the user builds the queue gradually
 this is also the main reason why I just don't save them because I still curating the videos & I don't want to manually save a half-assed list. coz it takes extra time. what I want is an auto progress save queue list function if somehow my browser gets crashed. I'll have peace of mind that yes my progress is still there I didn't lose anything. or I just want to restart my computer because of an update with this feature I can just close the browser and do the restarting process without thinking about how much I've lost! In the end, I want to say this feature is a huge one to boost the quality of one's mind. 

>this is not applicable because often the user builds the queue gradually, saving the queue each time the user adds a video doesn't make sense. The user needs to manually save the playlist after starting playing the queue using the menu.

literally what I'm requesting is the same as this https://chrome.google.com/webstore/detail/tab-session-manager/iaiomicjabeggjcfkbimgmglanimpnae

if you think the feature I'm requesting isn't applicable then the above extension wouldn't have gotten a user base of 60,000+ users.
so it makes sense to add this feature as there are lots of people who just can't or don't want to manually save the list. don't think about some users think about that 60,000+ & counting userbase.

**Comment by soufianesakhi** [comment]
So what I understand you want to autosave all opened playlists at regular intervals? This will require some time to implement, will open the issue for now for future implementation

**Comment by Droyk** [comment]
>So what I understand is you want to autosave all opened playlists at regular intervals?

Yup, & only if by playlists you mean queue lists doesn't matter if they are created manually 
![image](https://user-images.githubusercontent.com/15848350/126087086-3eeaf8fd-03be-4b08-873c-bda8cff431a2.png)
or by the extension. 

>autosave all opened playlists at regular intervals?
Well, that seems to be the method every extension on market is providing but wouldn't it be better to just save the progress only when a user adds the videos or remove videos from it? why bother saving it at regular intervals? though it would only be possible if the extension can detect the addition & removal of the video from the given list.

**Comment by soufianesakhi** [comment]
I'm afraid this is outside the scope of this extension. There are many other extensions that offer this functionality in a more generic way.

**Comment by Droyk** [comment]
>There are many other extensions that offer this functionality in a more generic way.

Can you please elaborate on that part! which extension provide this kind of functionality? I would love to use them.
I often go to the webstore both chrome & firefox hoping someone had made the thing I but I can't find it! please provide some links!!

**Comment by soufianesakhi** [comment]
Here are extensions that auto-save your browser session:
https://chrome.google.com/webstore/detail/tab-session-manager/iaiomicjabeggjcfkbimgmglanimpnae
https://chrome.google.com/webstore/detail/tabmanagerio-session-tab/hjicnemefbakbanoigbaonlpgflhggdf

**Comment by Droyk** [comment]
They will just save the tabs not the content inside those tabs like a queue list. & there's nothing in the store that offers the type of functionality I'm requesting & to say it's outside the scope of this extension when the name of the extension suggests otherwise. look I understand it's really hard to pull it off but think about how much time you will be saving of the users. if you don't care about that then you can see there's already a market for session managers. if you make this possible you will get a really big chunk of that userbase. and I really want this feature to happen I'm requesting you please reopen it and whenever you have enough time to brainstorm on this please do I'll be okay wait another year for this! just please don't say no to this!
