### ISSUE TITLE
[Feature Request] Automatically save the queue list last state 

### ISSUE THREAD

**Issue by Droyk** [soufianesakhi/youtube-playlist-helper#19]
As discussed in the previous request #9 
Please add a way to save its last state i.e. which video I was watching in the queue list? what state the video was in (paused, playing)? how much of the video I've watched? (i.e. exactly at what time I stopped watching it?)

Why automatic? easy coz I won't remember to hit the save button & since I crash my browser many times this feature combined with the playlist editor would be a great time saver.

**Comment by soufianesakhi** [comment]
This is too expensive to implement, maybe in the future there will be an internal video player and in this case saving the video state will be feasible.
