### ISSUE TITLE
[Enhancement request] Add option to disable image previews on playlists

### ISSUE THREAD

**Issue by Droyk** [soufianesakhi/youtube-playlist-helper#20]
![image](https://user-images.githubusercontent.com/15848350/125368098-24afcd00-e397-11eb-87b9-aa6994d2adb2.png)
Whenever I open the playlist editor & go to the saved playlist option it takes some seconds to load all the playlists & when I open the playlist. it takes few more seconds to populate all the saved videos. and if I want to open another playlist it's the same experience all over again.

So if possible please optimize the code otherwise It's not a big deal!

**Comment by soufianesakhi** [comment]
Hello, this is normal as the images need to be downloaded, nothing to optimize.

**Comment by Droyk** [comment]
hmm, How about providing an option on the top of the playlist editor page to not download the images as it takes time to load the playlists? only if possible.

**Comment by Droyk** [comment]
Wouldn't it be better to also add an option to make images visible after they are done downloading in the background? 
like show a skeleton and then after they are done downloading show them one by one or show them all together!
![image](https://user-images.githubusercontent.com/15848350/126086782-a0273aca-6685-47bb-aa67-7d887a85ed32.png)

- [ ] Disable image preview to save data usage & save time on loading while loading the playlists.
- [ ] Download & load all the images in the background!

**Comment by soufianesakhi** [comment]
Implemented in v2.3.0.
Note that when opening the editor page, the video data take some time to load (title, channel).

**Comment by Droyk** [comment]
Hmm, seems like you optimized your code a bit. now the playlists seem to open & populate in just 1-2 seconds. doesn't matter if the thumbnail previews are enabled or not. may I ask what did you change to get this much boost in loading time? why it took too much time before & why it doesn't take much time now?

**Comment by soufianesakhi** [comment]
I used a new way to get the data (oEmbed URL instead of direct video URL)
