### ISSUE TITLE
[Enhancement Request] Add "➤Saved Playlist" option in the Dropdown menu to access the saved playlists 

### ISSUE THREAD

**Issue by Droyk** [soufianesakhi/youtube-playlist-helper#21]
like a bookmark bar, one doesn't need to go to the bookmark page to open a single tab or a complete folder of tabs. 
by Adding a "➤Saved playlists" option in the dropdown menu user doesn't need to go to the playlist editor just to access all the saved playlists and their videos so the user can easily open any video from the list or the complete list. without opening a single page. it will Save Time! especially when the playlist editor takes a bit to load. 
Things to remember when implementing this option 
First, the right-click menu should work on the saved playlist menu. so the user can open whatever the user wishes to open (playlist or video) on a new tab, background tab, new window, or in a private window.
Second, add a trash bin icon just parallel to the video links and the playlist links. so the user doesn't need to go to the playlist editor page to simply delete the playlists or the videos inside the playlists.
third, it has to work in conjunction with the #19 feature means if the user opens a playlist via the dropdown menu it should open with its last saved state.

**Comment by soufianesakhi** [comment]
In v2.3.0, an option was added to choose the page that will be displayed when opening the playlist editor from the extension's popup. You can change the value to "Saved Playlists".

**Comment by Droyk** [comment]
Hmm, I was hoping to see something like this 
![image](https://user-images.githubusercontent.com/15848350/127871651-c08557c7-746d-4672-b800-7fcb5209c524.png)
![image](https://user-images.githubusercontent.com/15848350/127873343-a72ad435-0384-4911-bc8f-b24b78ba9662.png)

¯\\\_(ツ)_/¯

**Comment by Droyk** [comment]
@soufianesakhi 🥺
