### ISSUE TITLE
[Enhancement Request] Add an indication to show the playlist has been saved (✔️)

### ISSUE THREAD

**Issue by Droyk** [soufianesakhi/youtube-playlist-helper#22]
In the drop down menu
![image](https://user-images.githubusercontent.com/15848350/125376812-6ba6be00-e3a9-11eb-88f5-4bb60e43c23b.png)
![New Project](https://user-images.githubusercontent.com/15848350/125377553-d4426a80-e3aa-11eb-9ae8-840898aa2c72.png)
or 
via the extension badge 
![New Project](https://user-images.githubusercontent.com/15848350/125379926-0ce44300-e3af-11eb-9a13-eb8d40438c63.png)

it's confusing without indication, I wouldn't know without opening the playlist editor that my playlist has been saved or not. 
So by adding an indicator would solve the issue. The user doesn't need to open the playlist editor to see if it has been saved or not no confusion & it saves time.

If possible please add a real-time indicator so if it couldn't save the playlist for whatever reason. it should show the user it couldn't save the list. so the user find another way to save the list.

**Comment by soufianesakhi** [comment]
There is already a notification displayed when saving a playlist or on error. The native operating system is used to display the notification (for more info, see the [notification API docs](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API).
Please ensure that the OS notifications were not disabled in your browser.

**Comment by Droyk** [comment]
Hmm, I usually keep the native notification system in a priority-only mode coz of too many notifications so it doesn't deter my focus. It would be nice to have a dynamic extension badge.    
![image](https://user-images.githubusercontent.com/15848350/127868212-de28a364-dc43-443b-9d1f-2e39d3a43425.png)

**Comment by Droyk** [comment]
So after using the extension regularly for a period of 2 months, this feature needs redundancy. since I'm on the priority-only mode the notification doesn't show so I have to click on the notification menu to see if my playlist has been saved or not. now I can put Microsoft edge on the priority-only list mode but that would mean I would see all the youtube notifications and other extension notifications as well which I don't want to see pop up on my screen because it deters my focus. so it would be better to add an indication of it via the extension badge or the dropdown menu!

**Redundancy is a good thing!**
