### ISSUE TITLE
[Feature Request] Better way to add individual videos! 

### ISSUE THREAD

**Issue by Droyk** [soufianesakhi/youtube-playlist-helper#24]
for the past few weeks, I've been using your extension a lot. it solves some problems & adds some unique problems of its own. like sometimes I just want to watch 7 to 8 videos from the list of let's say 50 videos and make a new queue out of it or just add them to the current list. the problem is there is no easy way to do this.
"Create a playlist from the current tab youtube video thumbnails" isn't going to work for the obvious reason.
"Create a playlist from the list of links" could've worked if it was implemented correctly & even if it was implemented correctly it would still be time-consuming coz copy-pasting of the list of links. 
"Create a playlist by right-clicking and load in the background and use "Combine youtube tabs & create a playlist" that's what I've been using & it's a resource-intensive method.
so it would be convenient if you can add a way to make this possible so whenever the mouse cursor hovers over a youtube link/ thumbnail or the title of the video anywhere on the web (it doesn't matter if it's on a google search page, or duckduckgo's or on bing or somewhere on Reddit or on Github or on youtube itself) 2 types of small icons should appear just next to the cursor, first one should be a dynamic one. so whenever the user clicks on it. it makes a new current session playlist & adds the currently selected link to the playlist. it should be telling us how many videos we have so far in that playlist just like these extension badges does 
![image](https://user-images.githubusercontent.com/15848350/128081307-116f5f2a-19f5-48f7-9839-1f4d5e75a1d6.png)
& the other one is a play button to watch all of the videos that I just added in the current session playlist using the first icon (the dynamic one). if I don't want to watch them right now. I know it has been saved in the playlist editor so whatever happens, I can always just go to the playlist editor to watch them & do the other work tension-free. 

Please really think about this it's a very time-saving feature.

**Comment by Droyk** [comment]
@soufianesakhi Hey, is there any news on my request? 
most importantly, what do you think about this feature? are you working on it?

**Comment by Droyk** [comment]
Bumping! anything? dying to use this feature! @soufianesakhi

**Comment by soufianesakhi** [comment]
This will be implemented soon using a right-click context menu on YouTube links and videos

**Comment by Droyk** [comment]
The context menu option is great for accessibility. as many options as you can add to add individual videos is a great addition. but wouldn't it be convenient to add a popup menu just like this one https://gfycat.com/grouchygoodantelopegroundsquirrel
to add the individual videos and within that popup menu add the options that says add into the current list or the saved playlist (i.e. saved in the playlist editor)
or play now with the current queue list.

**Comment by Droyk** [comment]
The context menu option is great for accessibility. as many options as you can add to add individual videos are a great addition. but wouldn't also it be convenient & time saving to add a popup menu just like this one https://gfycat.com/ifr/grouchygoodantelopegroundsquirrel/?hd=1
to add the individual videos and within that popup menu add the options that say add into the current list or the saved playlist (i.e. saved in the playlist editor)
or play now with the current queue list.

by adding a popup menu Users can experience smooth and consistent experiences throughout their video-watching time. in comparison right-click context menu feels tedious when the user is in the rush and there are many videos that they want to add to the list. adding a hoverable popup means one less step to do.

**Comment by soufianesakhi** [comment]
Implemented starting from v2.6.0

**Comment by Droyk** [comment]
> Implemented starting from v2.6.0

Something tells me that this https://gfycat.com/ifr/artisticamusingcaiman?hd=1&controls=0 isn't the intended behavior. Please tell me that this isn't the intended behavior!!

**Comment by Droyk** [comment]
> Implemented starting from v2.6.0

Something tells me that this https://gfycat.com/ifr/artisticamusingcaiman?hd=1&controls=0 isn't the intended behavior. Please tell me that this isn't the intended behavior!!  
@soufianesakhi Are the users supposed to copy-paste the links to the playlist builder if so I don't see any point to add a context menu entry just for this may be good accessibility but still, I could've just opened the popup and open editor to paste the link. & let it remain open in the background so I can just copy-paste the links. it doesn't make any difference at all!

I hope I'm wrong!

**Comment by soufianesakhi** [comment]
Can you copy the link you are trying to add to the playlist using the right-click context menu from google search results ? only YouTube direct links are supported

**Comment by soufianesakhi** [comment]
Depending on the browser, video results from google search results are not YouTube direct links, so they are not supported. You can install some extension or user script to have direct google links, and then use the playlist builder.

**Comment by soufianesakhi** [comment]
Firefox: https://addons.mozilla.org/addon/dont-track-me-google1/
Chrome: https://chrome.google.com/webstore/detail/dont-track-me-google/gdbofhhdmcladcmmfjolgndfkpobecpg

**Comment by Droyk** [comment]
for a second there I thought that's all we are gonna get! it's working. but if it needs direct links then why it works via the option to "scan the current tab for youtube links and create a playlist"? it shouldn't also work there! why you didn't add the converting feature (tracking link to direct one) for this option? is this something you're working on right now?
because hardly any user will have a link sanitizer! other than tech-savvy users!
