### ISSUE TITLE
[Suggestion] Replace the current naming scheme with "Youtube Queue maker/creator/builder" or "Utube Queuer"   

### ISSUE THREAD

**Issue by Droyk** [soufianesakhi/youtube-playlist-helper#27]
The name Youtube Playlist helper doesn't sound like a great one. as for why it isn't coz it isn't specifying what it actually does. while "Youtube Queue maker/creator/builder", "Utube Queuer" or Youtube list manager!

immediately tells the user what it is. now to know more about it as for what it does they simply need to open the extension page & see the description of it. a simple description for the youtube list manager would be Manages your youtube list(Playlist/Queue list) like no/none other!

if that above sounds good then It would be better if you introduce the change with these features #24 #18

**Comment by soufianesakhi** [comment]
Thanks for the suggestion, but I'm not open to it for the moment
