### ISSUE TITLE
[Feature Request] Play All Videos in Youtube Queue

### ISSUE THREAD

**Issue by Enderlold** [soufianesakhi/youtube-playlist-helper#28]
Play all videos, but Youtube queue version
![image](https://user-images.githubusercontent.com/89827287/141995872-6902772c-62b8-4c2e-ba73-bf41a2bbfa43.png)

When I try to play all playlist having over 50 videos, playlist will be separated, and MANY TABS.
If I can play all list with no separating, it will be great. But I thought it was hard to make it.
Then I thought that play in Youtube queue would be a good alternative.

I love this extension, this is very useful! Thank you for making this! :D
And take care of yourself, it's very cold these days (at least in my country).

**Comment by Enderlold** [comment]
Update: I don't meant to replace the feature, I just want new option.

**Comment by soufianesakhi** [comment]
Hello, it's not possible using a YouTube queue, but in the future there may be a way to play playlists with more than 50 videos within the extension
