### ISSUE TITLE
[feature request] add a button to play saved playlist

### ISSUE THREAD

**Issue by joshatt** [soufianesakhi/youtube-playlist-helper#29]
I'm trying to figure out how to use this in Android Kiwi browser, in order to reverse play any given playlist.
It seems that "queue" does not make sense in this android browser.
After playing around a bit, I found this: when in a playlist, "scan current tab for youtube links and create a playlist", thus I got a playlist merely inside this extenstion, not in youtube page, then "open playlist editor" and I could reverse this saved playlist and save it, now I think I'm close to success, but there's no way to play it, since this playlist merely exist in this extension. I noticed there are 5 buttons with this playlist - add, copy, reverse, save, delete. Will adding a "play" button fulfill my need?

**Comment by soufianesakhi** [comment]
Sorry but only desktop web browsers are supported at the moment
