### ISSUE TITLE
Youtube playlists only go up to 50 videos

### ISSUE THREAD

**Issue by DesperatePea** [soufianesakhi/youtube-playlist-helper#30]
The playlist i created is 109 videos. However, when i click on "play videos" it splits the playlist in 3 separate lists. Can this system only make a playlist that go up to 50 vids?

**Comment by soufianesakhi** [comment]
This is currently not supported by YouTube itself because anonymous playlists have a limit of 50 videos, but maybe in the future there will be alternative way to play playlists from the extension
