### ISSUE TITLE
[Bug] when the URL doesn't change to the queue list one, it shows an Error!

### ISSUE THREAD

**Issue by Droyk** [soufianesakhi/youtube-playlist-helper#31]
That says the current tab is not a Youtube playlist tab! when in fact it is 
![image](https://user-images.githubusercontent.com/15848350/147375849-38008fd6-2f18-496b-8ede-1eb1cc2356c9.png)
To fix it the user can just refresh the page or go to the next video in the queue.

when there's only one queue list it's not annoying but when there's 5 to 10 queue list it gets annoying really fast!
easily reproducible too. go to any video page lets say https://www.youtube.com/watch?v=Y9dr2zw-TXQ now just add the videos from the sidebar.

**Comment by soufianesakhi** [comment]
Fixed in v2.6.1

**Comment by Droyk** [comment]
after creating the playlist it immediately opens the playlist editor page which is great in my opinion but there is no option to disable it. please add an option to disable it on the settings page!
