### ISSUE TITLE
Feature Request: Instead of making an untitled playlist make a queue to eliminate the 50 video CAP!

### ISSUE THREAD

**Issue by Droyk** [soufianesakhi/youtube-playlist-helper#34]
So I binge a lot of youtube channels & to watch every single video as quickly as possible I hit scan the current tab for youtube links and create a playlist 
![image](https://user-images.githubusercontent.com/15848350/150591059-5fe5a2d0-e7dc-4ca1-8980-c298aef1e61b.png) 
the problem is it creates multiple playlists tabs. if the page has 110 videos then it will create 3 playlist tabs consisting of 50,50,10. instead of this wouldn't it be better to create a queue coz it doesn't have that problem it eliminates the 50 video cap
![image](https://user-images.githubusercontent.com/15848350/150591498-65702a7a-cd8b-4912-9fc8-a68af9fba779.png)

**Comment by soufianesakhi** [comment]
This is not technically possible

**Comment by Droyk** [comment]
Sad.
