### ISSUE TITLE
Ошибка/Error (

### ISSUE THREAD

**Issue by vzdhd** [soufianesakhi/youtube-playlist-helper#4]
Здравствуйте! 
В браузере edge закрылись все открытые вкладки (не только youtube) и открылась страница с ошибкой "Сейчас эта страница не работает Если проблема не исчезнет, обратитесь к владельцу сайта." HTTP ERROR 400

Hello!
The edge browser closed all open tabs (not just youtube) and opened a page with the error " Now this page does not work if the problem persists, contact the site owner." HTTP ERROR 400

**Comment by soufianesakhi** [comment]
I found the issue. The url of the extension `https://chrome.google.com/webstore/detail/youtube-playlist-helper/ibdakohjhchaagmccfedeejmeillongg/related` is being treated as a YouTube url.
As a workaround you can close it before generating the playlist, I will fix the issue later.

**Comment by soufianesakhi** [comment]
Fixed in  v1.2.1
