### ISSUE TITLE
Playlist disappeared.

### ISSUE THREAD

**Issue by WYNDFURY** [soufianesakhi/youtube-playlist-helper#6]
Hey there!

I used your addon on firefox like 3days ago and it worked like a gem, thanks a lot!
One thing though, my playlists disappeared today, the links that worked and even used on a discord bot are now links that redirect me towards only one music and not the 50musics playlist anymore.

Is there a way for me to save that playlist? (Like a normal usual youtube playlist)
Thanks in advance!

**Comment by soufianesakhi** [comment]
Hello,
Yes this possible by:
1. Checking the following options then clicking save from the add-on's options:
![1](https://user-images.githubusercontent.com/17222854/94351478-2eab4e00-0059-11eb-82a4-0f9f9c6a7604.PNG)
2. Creating a new playlist from the generated playlist as follows:
![2](https://user-images.githubusercontent.com/17222854/94351490-484c9580-0059-11eb-9899-ff415e451e9e.png)

**Comment by WYNDFURY** [comment]
Damn, thanks a lot!
Cleans explanations, worked perfectly.

**Comment by soufianesakhi** [comment]
You're welcome
