### ISSUE TITLE
Don't erase/delete/destory old playlist for the new videos

### ISSUE THREAD

**Issue by Droyk** [soufianesakhi/youtube-playlist-helper#7]
Umm so recently installed your extension worked as described. the problem is If there's already an old playlist created by this extension. it doesn't add videos to it or make a new playlist. it just destroy that playlist make a new playlist & I learned that hard way! so please make it recognize that there is a playlist in the current window, give a choice to the user to add the videos to the same playlist or make a new one. 

I'm on Edge btw Version 88.0.705.68 (Official build) (64-bit)

**Comment by soufianesakhi** [comment]
Thanks for opening an issue.
I don't think I understood it well.
Are you trying to create a playlist from an already open playlist tab?
Which option of the extension are you using?

**Comment by Droyk** [comment]
>I don't think I understood it well.

Forgive me as I'm not a good writer. 
>I don't think I understood it well.

I created a playlist using the option "create a playlist from currently opened youtube tabs" & it did what it described now the problem is If I opened another set of videos on different tabs not on the different window on the same window & again want to use your extension to make the playlist then now what will happen is it will destroy the old playlist & make a new one. 

you can just reproduce it first make a playlist using the option  "create a playlist from currently opened youtube tabs"
now on the same window open the 3-4 youtube video tab & make the playlist using  "create a playlist from currently opened youtube tabs" you'll see that it has destroyed the old playlist for the new one!

What I want from you is to make your extension recognize that there is already a playlist in the current window when the user wants to make a new playlist, give a choice to the user to add the videos to the same playlist or to make a new one.

**Comment by soufianesakhi** [comment]
I will try to fix it as soon as possible.

**Comment by soufianesakhi** [comment]
Fixed in the 1.4.0 version :)

**Comment by Droyk** [comment]
thankyou! it does the work but if there's a way to ask to add in the current or make a new one please add it!

**Comment by Droyk** [comment]
thankyou! it does the work but if there's a way to ask to add it to the current playlist or make a new one please add it!
you can just provide a choice inside this ![image](https://user-images.githubusercontent.com/15848350/108682470-558d8380-7516-11eb-979d-1ee2bfb83d32.png) option to 
➤ make a new playlist 
or 
➤ to add it to the current one 

P.S. what does "disable_polymer"option function does?

**Comment by soufianesakhi** [comment]
Hello,
I can implement something like this: Combine other youtube tabs with the current playlist
This will create a new playlist using the current playlist's videos in addition to the other open youtube video tabs. If this is something you would like to be implemented, you can create a new issue :)

The "disable_polymer" option adds a query parameter to the created playlist's URL (&disable_polymer=1). It was useful in conjunction with the "Open playlist page" option because the old layout had an option to add current playlist video to an existing user playlist (it was a request from a user), but this can no longer be done.

**Comment by Droyk** [comment]
>The "disable_polymer" option adds a query parameter to the created playlist's URL (&disable_polymer=1). It was useful in conjunction with the "Open playlist page" option because the old layout had an option to add current playlist videos to an existing user playlist (it was a request from a user), but this can no longer be done.

just remove it then if it's not providing any benefit because now it just creates unnecessary confusion as there is no explanation present in the options page as to what this option does?
