### ISSUE TITLE
[Feature request] Provide an option to add the videos to the current playlist or to make a new one!

### ISSUE THREAD

**Issue by Droyk** [soufianesakhi/youtube-playlist-helper#8]
What I want from you is to give a choice to the user to add the videos to the same playlist or to make a new one.

as discussed here #7  

>I can implement something like this: Combine other youtube tabs with the current playlist.
This will create a new playlist using the current playlist's videos in addition to the other open youtube video tabs. If this is something you would like to be implemented.

I like the idea! plz, go forward! also, be sure that there's a choice either to create a new one automatically. if there's a playlist present which you've already fixed #7 (what I mean is don't destroy the previous feature) now the only thing is left to add the above function
>Combine other youtube tabs with the current playlist.
& everything will be alright!

**Comment by soufianesakhi** [comment]
This was implemented in v1.5.0 :)
