### ISSUE TITLE
[Feature Request] Automatically save created playlist by this extension & it's last state!

### ISSUE THREAD

**Issue by Droyk** [soufianesakhi/youtube-playlist-helper#9]
I lost 86 videos in 4 different playlists the amount of knowledge I could've gained! 
it hurts! well, I work with lots of tabs sometimes 100+ and I procrastinate a lot. the above things happen to me a lot of times & so I was wondering if you can add a way to save the playlist & its last state what I mean by that is you're basically making a youtube queue list, right? the biggest downside is it doesn't save the videos even when the URL is intact (it has a unique URL (list=TLPQMjgwMjIwMjG9Vi5aZ9BUew)) what I want is a way to save those videos & if possible don't save them in the account coz if I don't like any video in the playlist I'll have to go back and delete the whole playlist from my account which is an annoyance too so if possible save it using the extension memory this way the users also can take the advantage of chrome sync which will be an added bonus if I want to listen to the same playlist using my mobile this way I can and I don't have to save it!
the other request is to save the last state of the playlist i.e. which video I was watching? what state the video was in (paused, playing)? this will really help my productivity & others like me! please make it possible!
when the next user opens the browser restore the queue list URL & voila everything is back!

**Comment by soufianesakhi** [comment]
I have disabled tab closing by default and added an option if the user wants to close tabs after creating playlists.
Can this solution be a good alternative to the feature you described here ?

**Comment by Droyk** [comment]
I think you took a really easy way on this & I really don't think so that's gonna help in any way. It's a good thing there's a choice for the user to close the tabs or let them be there but Since I'm a tab hoarder I usually have low memory so whenever I hit your extension. if it's not gonna close all the other tabs & gonna create a new one means it will need additional processing power, more memory which can do two things crash memory consuming pages or just crash the whole browser. this happens If I'm already running on low memory(ram) + storage memory(ssd). now if it crashes the whole browser I may have all the tabs but what about the progress I made? I'll have to recreate the playlist which will take time. un-convenient! now this time if I choose the option "close tabs after combine" & somehow the browser crashes coz of low memory the same thing will happen again all the progress I made is lost! I'll have to recreate the whole playlist! 

& I think it would be way better if you can add all the options somewhere in the below frame coz there only 2 options which makes it really silly to tell the user to go to a special page to access them. this will be a huge + for UX! would be really time-saving & convenient!
![image](https://user-images.githubusercontent.com/15848350/110398853-ba121c00-809a-11eb-9023-7fdf5d4f2c06.png)

**Comment by soufianesakhi** [comment]
This will be implemented once the playlist editor feature I'm currently working on is complete

**Comment by Droyk** [comment]
any progress?

**Comment by soufianesakhi** [comment]
Yes I am close to publishing it (either this week or next week)

**Comment by soufianesakhi** [comment]
I have released the 2.0.0 version that includes the playlist editor. The generated playlists are saved and can be viewed in the playlist editor's recently created playlists page. The playlist's current playing video state is not saved as it's too ambiguous and not straightforward. If this is something you really need, I invite you to open a new issue.
